### ISSUE TITLE
file/popen is deprecated

### ISSUE THREAD

**Issue by LeviSchuck** [bakpakin/mendoza#18]
Looks like a small update is warranted

```
/usr/local/lib/janet/mendoza/init.janet:188:15: compile warning (normal): file/popen is deprecated
/usr/local/lib/janet/mendoza/init.janet:199:13: compile warning (normal): file/popen is deprecated
```

This comes up when running `mdz serve`

**Comment by sogaiu** [comment]
@LeviSchuck I think uses of `file/popen` may have been removed [here](https://github.com/bakpakin/mendoza/commit/2b6f5bc902187ef179e9a6bbc756a92403c28ad0).

If that looks ok to you, may be this can be closed?

**Comment by LeviSchuck** [comment]
This issue is resolved as of https://github.com/bakpakin/mendoza/commit/2b6f5bc902187ef179e9a6bbc756a92403c28ad0 
Thank you @sogaiu for identifying it.
