### ISSUE TITLE
jpm install fails

### ISSUE THREAD

**Issue by semperos** [bakpakin/mendoza#4]
* macOS Catalina 10.15.1
* `brew install janet`
* `janet -v` prints `1.4.0-meson`

When I execute `jpm install https://github.com/bakpakin/mendoza.git` (with or without `sudo`) at the command-line, I see:

```
Error building git repository dependency: No such file or directory
```

**Comment by bakpakin** [comment]
I haven't tried the latest macOS, but I suspect the issue may be related to file permissions. I hope to get Catalina installed on my old macbook that I pulled out of the closet and look in to this on a fresh install this weekend. Another possibility is the homebrew package needs fixing.

**Comment by bakpakin** [comment]
Seems to be an issue with `meson` not creating a needed directory when installing. The homebrew formula also does not create this directory. The quick solution is to `mkdir /usr/local/lib/janet`. I will fix this in the next release of Janet
